try:
    result = 12/0
except:
    print("a error happend")
print("done")